apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-deployment
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/lucasmleone/argocd-example-apps.git'
    targetRevision: master
    path: guestbook
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
